name: Deploy and Configure

on:
  push:
    branches: [ main ]

jobs:
  # terraform:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: hashicorp/setup-terraform@v3
  #     - name: Set Azure Credentials
  #       run: |
  #         echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
  #         echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
  #         echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
  #         echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
  #     - name: Azure Login
  #       run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
  #       env:
  #         ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
  #         ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
  #         ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
  #     - name: Terraform Init
  #       run: terraform init -upgrade
  #       working-directory: terraform
  #     - name: Terraform Plan
  #       run: terraform plan -out=tfplan
  #       working-directory: terraform
  #     - name: Terraform Apply
  #       run: terraform apply -auto-approve tfplan
  #       working-directory: terraform
  #     - name: Get IP
  #       id: ip
  #       run: echo "ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
  #       working-directory: terraform

  ansible:
    # needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ansible
        run: sudo apt update && sudo apt install ansible -y
      - name: Update Inventory
        run: echo "[vm]\n4.225.169.223 ansible_user=${{ fromJSON(secrets.VM_CREDENTIALS).vmUser }} ansible_ssh_pass=${{ fromJSON(secrets.VM_CREDENTIALS).vmPassword }}" > ansible/inventory.ini
        env:
          VM_IP: ${{ vars.VM_IP }}
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          KC_DB: ${{ secrets.KC_DB }}
          KC_DB_URL: jdbc:postgresql://postgres/keycloak
          KC_DB_USERNAME: ${{ secrets.KC_DB_USERNAME }}
          KC_DB_PASSWORD: ${{ secrets.KC_DB_PASSWORD }}
          KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
          KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
          VM_IP: 4.225.169.223
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
